{% set name = "refinenet" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a32d4d73e56dccf1c1129b5c61aa61846ac5163e9b107ee2db360b9b5c77b1e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - acrv_datasets
    - numpy
    - pillow
    - pycocotools
    - python >=3.6
    - pytorch 
    - scipy
    - six
    - torchvision

test:
  imports:
    - refinenet
    - refinenet.datasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/best-of-acrv/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: RefineNet is a multi-path refinement network for semantic image segmentation
  description: |
    RefineNet is a generic multi-path refinement network for high-resolution
    semantic image segmentation and general dense prediction tasks on images.
    It achieves high-resolution prediction by explicitly exploiting all the
    information available along the down-sampling process and using long-range
    residual connections. It includes a Python API, & scripts for command line
    usage.
  doc_url: https://github.com/best-of-acrv/{{ name }}
  dev_url: https://github.com/best-of-acrv/{{ name }}

extra:
  recipe-maintainers:
    - btalb
